site_name: Topic Modeling Project
site_description: Automated topic modeling with LDA and NMF algorithms
site_url: https://yourusername.github.io/topic-modeling-project
repo_url: https://github.com/yourusername/topic-modeling-project
repo_name: yourusername/topic-modeling-project

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github

plugins:
  - search:
      lang: en
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_root_toc_entry: true
            show_object_full_path: true
            show_category_heading: true
            show_if_no_docstring: false
            members_order: source
            filters: ["!^_"]
            merge_init_into_class: true
            show_signature_annotations: true
            separate_signature: true
            line_length: 88

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - pymdownx.caret
  - attr_list
  - md_in_html
  - toc:
      permalink: true
      title: On this page
      toc_depth: 3

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/your-package-name

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
  - User Guide:
    - Data Preprocessing: user-guide/data-preprocessing.md
    - Topic Modeling: user-guide/topic-modeling.md
    - Model Evaluation: user-guide/model-evaluation.md
  - API Reference:
    - Overview: api/index.md
    - Data Processing: api/data.md
    - Topic Models: api/topics.md
    - Features: api/features.md
    - Models: api/models.md
    - Utils: api/utils.md
  - Examples: examples.md
  - Contributing: contributing.md